import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Open_Sans } from "next/font/google";

import { ClerkProvider } from "@clerk/nextjs";
const frontendApi = 'pk_test_cGVyZmVjdC1yYWJiaXQtMzcuY2xlcmsuYWNjb3VudHMuZGV2JA';
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";

import { cn } from "@/lib/utils";
// const inter = Inter({ subsets: ["latin"] });

const font = Open_Sans({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: "Team_27",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider >
      <html lang="en" suppressHydrationWarning>
        <body className={ cn(
          font.className,
          "bg-white dark:bg-[#313338]"
        )}>
          {/* add newly created theme components */}
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem={false}
            storageKey="discord-theme"
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
